# Generated by Django 5.2.7 on 2025-11-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_semana', models.DateField()),
                ('fin_semana', models.DateField()),
                ('total_semana', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
    ]
